---

- name: Ensure that the application file permissions are set properly
  file: path={{ flask_virtualenv_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  changed_when: False
