---
git_repo: https://github.com/DavidCain/mitoc-trips.git
setup_git_repo: yes

# Virtualenv settings.
enable_deadsnakes_ppa: no
recreate_virtualenv: yes
virtualenv_python_version: python3.6


# Application settings.
virtualenv_path: "/webapps/{{ django_application_name }}"
project_path: "{{ virtualenv_path }}/{{ django_project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
django_error_file: "{{ application_log_dir }}/django_errors.log"
ws_lottery_log_dir: "{{ application_log_dir }}/ws_lottery_runs"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings.
gunicorn_user: "{{ django_application_name }}"
gunicorn_group: webapps


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEMBERSHIP_SECRET_KEY: "{{ membership_secret_key }}"
  DJANGO_ERROR_FILE: "{{ django_error_file }}"
  WS_LOTTERY_LOG_DIR: "{{ ws_lottery_log_dir }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  AUTH_DATABASE_NAME: "{{ auth_db_name }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_HOST: "{{ db_host|default('localhost') }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  GEAR_DATABASE_NAME: "{{ gear_db_name }}"
  GEAR_DATABASE_USER: "{{ gear_db_user }}"
  GEAR_DATABASE_PASSWORD: "{{ gear_db_password }}"
  GEAR_DATABASE_HOST: "{{ gear_db_host|default('localhost') }}"
  SES_USER: "{{ ses_user|default('') }}"
  SES_PASSWORD: "{{ ses_password|default('') }}"
  BROKER_URL: "{{ broker_url }}"
  OAUTH_JSON_CREDENTIALS: "{{ project_path }}/oauth_credentials.json"
  RAVEN_DSN: "{{ raven_dsn|default('') }}"
  WS_DJANGO_LOCAL: "{{ django_debug|default('') }}"
  EC2_IP: "{{ ec2_ip|default('') }}"
  DOCUSIGN_API_BASE: "{{ docusign_api_base|default('') }}"
  DOCUSIGN_USERNAME: "{{ docusign_username|default('') }}"
  DOCUSIGN_PASSWORD: "{{ docusign_password|default('') }}"
  DOCUSIGN_INTEGRATOR_KEY: "{{ docusign_integrator_key|default('') }}"
  DOCUSIGN_WAIVER_TEMPLATE_ID: "{{ docusign_waiver_template_id|default('') }}"
