---
flask_git_repo: https://github.com/DavidCain/mitoc-member
setup_git_repo: true

# Application settings.
virtualenv_python_version: python3.6
flask_virtualenv_path: "/webapps/{{ flask_application_name }}"
flask_project_path: "{{ flask_virtualenv_path }}/{{ flask_project_name }}"
flask_application_log_dir: "{{ flask_virtualenv_path }}/logs"
flask_application_log_file: "{{ flask_application_log_dir }}/gunicorn_supervisor.log"
flask_requirements_file: "{{ flask_project_path }}/requirements.txt"


# Gunicorn settings.
gunicorn_user: "{{ flask_application_name }}"
gunicorn_group: webapps


# Nginx settings.
api_access_log_file: "{{ flask_application_log_dir }}/api_nginx_access.log"
api_error_log_file: "{{ flask_application_log_dir }}/api_nginx_error.log"
mutual_tls_access_log_file: "{{ flask_application_log_dir }}/tls_nginx_access.log"
mutual_tls_error_log_file: "{{ flask_application_log_dir }}/tls_nginx_error.log"


# Flask environment variables.
flask_environment:
  CYBERSOURCE_SECRET_KEY: "{{ cybersource_secret_key }}"
  VERIFY_CYBERSOURCE_SIGNATURE: "{{ verify_cybersource_signature|default('true')}}"
  MEMBERSHIP_SECRET_KEY: "{{ membership_secret_key }}"
  GEAR_DATABASE_NAME: "{{ gear_db_name }}"
  GEAR_DATABASE_USER: "{{ gear_db_user }}"
  GEAR_DATABASE_PASSWORD: "{{ gear_db_password }}"
  GEAR_DATABASE_HOST: "{{ gear_db_host|default('localhost') }}"
  RAVEN_DSN: "{{ flask_raven_dsn|default('') }}"
